name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17 (JDK)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          java-package: jdk  # You can choose jdk or adopt
          distribution: 'adopt'

      - name: Set up Google Cloud SDK (unchanged)
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: 7284c2010b5dc3f2ad21bc298a543e1b47429a4b
          export_default_credentials: true

      # Replace the following steps with commands specific to your Spring Boot build and deployment
      - name: Build with Maven (replace with your commands)
        run: |
          mvn clean package  # You might need additional goals like mvn test
      - name: Deploy to Google App Engine (replace with your commands)
        run: |
          gcloud app deploy
        # ... (commands to deploy your artifact to Google App Engine)


#      - name: Build and deploy (with minimal logging)
#        run: |
#          ./gradlew assemble
#          gcloud app deploy --verbosity=info
